name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache Python dependencies and Databricks CLI
      - name: Cache dependencies and CLI
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/bin
            ~/.cache/pip
          key: cli-cache-${{ runner.os }}
          restore-keys: cli-cache-${{ runner.os }}-

      # Set up Databricks CLI if cache is not hit
      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main
        if: steps.cache.outputs.cache-hit != 'true'

      # Validate Databricks bundle
      - name: Validate Bundle
        run: databricks bundle validate || { echo "Bundle validation failed"; exit 1; }
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

  deploy_to_development:
    runs-on: ubuntu-latest
    needs: install_and_test
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache Python dependencies and Databricks CLI
      - name: Cache dependencies and CLI
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/bin
            ~/.cache/pip
          key: cli-cache-${{ runner.os }}
          restore-keys: cli-cache-${{ runner.os }}-

      # Set up Databricks CLI if cache is not hit
      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main
        if: steps.cache.outputs.cache-hit != 'true'

      # Deploy to development environment
      - name: Deploy to Development
        run: databricks bundle deploy --target dev --auto-approve
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

  deploy_to_production:
    runs-on: ubuntu-latest
    needs: install_and_test
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://example.com/production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache Python dependencies and Databricks CLI
      - name: Cache dependencies and CLI
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/bin
            ~/.cache/pip
          key: cli-cache-${{ runner.os }}
          restore-keys: cli-cache-${{ runner.os }}-

      # Set up Databricks CLI if cache is not hit
      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      # Deploy to production environment (manual trigger)
      - name: Deploy to Production (Manual Trigger)
        run: databricks bundle deploy --target prod --auto-approve
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
