name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies and CLI
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/bin
            ~/.cache/pip
          key: cli-cache-${{ runner.os }}
          restore-keys: cli-cache-${{ runner.os }}-

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main
        if: steps.cache.outputs.cache-hit != 'true'

  validate:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Validate Bundle
        run: databricks bundle validate || { echo "Bundle validation failed"; exit 1; }
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

  deploy_to_development:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy to Development
        run: databricks bundle deploy --target dev --auto-approve
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

  deploy_to_production:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Production (Manual Trigger)
        run: databricks bundle deploy --target prod --auto-approve
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
